# Generated by Django 5.0 on 2023-12-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_studentuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='gender',
            field=models.CharField(max_length=15),
        ),
    ]
