# Generated by Django 5.0 on 2023-12-26 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_recruiter_image_alter_studentuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('salary', models.FloatField(max_length=100)),
                ('image', models.ImageField(upload_to='bg_images/')),
                ('description', models.CharField(max_length=400)),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.recruiter')),
            ],
        ),
    ]
