# Generated by Django 5.0 on 2023-12-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_studentuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(upload_to='profile/bg_images/'),
        ),
    ]
