# Generated by Django 5.0 on 2023-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='profile/bg_images/'),
        ),
    ]
