# Generated by Django 5.0 on 2023-12-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='bg_images/'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(upload_to='profile/bg_images/'),
        ),
    ]
