# Generated by Django 5.0 on 2023-12-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_job_image_alter_studentuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(upload_to='bg_images/'),
        ),
    ]
