# Generated by Django 5.0 on 2024-01-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_alter_job_image_alter_recruiter_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
